AWSTemplateFormatVersion: 2010-09-09
Parameters:
  DbPasswordParam:
    Type: String
    Default: /Dev/Db/admin
Resources:
  DB:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t2.small
      Engine: MySQL
      MasterUsername: admin
      MasterUserPassword:
        Fn::Transform:
         - Name: GenerateSecret
           Parameters:
             SecretName: !Ref DbPasswordParam
             Exclude:
              - '"'
              - '/'
              - '@'

