AWSTemplateFormatVersion: 2010-09-09
Description: Resources to be used by CI CodeBuild Projects
Parameters:
  DevHelmChartRepoBucketName:
    Type: String
    Default: bct-b4cs-dev-helm-repo
Resources:
  DevHelmChartRepoBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${DevHelmChartRepoBucketName}
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 45
            Status: Enabled

  DevHelmChartRepoBucketParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/Build/Ci/HelmChartRepoUrl"
      Type: String
      Value: !Sub s3://${DevHelmChartRepoBucket}/

  CiCodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: buildPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*:*
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:Put*
                  - s3:List*
                Resource:
                  - !Sub ${DevHelmChartRepoBucket.Arn}
                  - !Sub ${DevHelmChartRepoBucket.Arn}/*
              - Effect: Allow
                Action:
                  - eks:Describe*
                  - eks:List*
                Resource:
                  - "*"
              - Effect: Allow
                Action:
                  - ssm:GetParameters
                Resource:
                  - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/Build/*
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser

  CiCodeBuildRoleParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/Build/Ci/CodeBuildRoleArn"
      Type: String
      Value: !Sub ${CiCodeBuildRole.Arn}